### ISSUE TITLE
can it be collected of the the choices?

### ISSUE THREAD

**Issue by jinsyu** [Michelphoenix98/conditional_questions#6]
i am plannig to make research app that have more than 200 nested questions. it need to be colleted to server. and make a report based on the results. 
i want to know the that this package will provide that features soon or not. thx for your dedication.

**Comment by Michelphoenix98** [comment]
Hi,

Could you please be more specific?
When you say 200 nested questions, do you mean questions that are 200 level
deep or the number of questions?
Also, there's a 'toMap' function that can be called to produce a json
object with the collected answers that can be sent over to the server for
storage.

**Comment by jinsyu** [comment]
200 questions with some few levels. to get results should i have to make variables each of them? its gonna be hundreds, so i am looking packages to get results easily. i found https://pub.dev/packages/research_package it works great. but it does not provide multiple question branches. i hope you understand what i mean.

**Comment by Michelphoenix98** [comment]
I think I know what you mean, yes. My package can branch and yes you can
branch as many times as you want.
You won't have to create a hundred variables and manage them at the same
time.
Check out this article, it'll show you how to set it up.
https://michelphoenix98.medium.com/implementing-a-simple-survey-app-with-conditional-questions-in-flutter-4c31e95b7040
Also check out the examples;
https://github.com/Michelphoenix98/conditional_questions/blob/master/example/README.md
The questionnaire_firestore example deals with uploading data to Firebase.
Clone and run the first or third example to see if that's what you're
looking for.

**Comment by jinsyu** [comment]
works like a charm!.
one more asking... i want it to be seperated with key and question value. my question wolud be "What is your name?" and its gonna be firestore field name. it does not ok to fetching data. my asking is every type of Question class have key parameter and its going to be firestore field name. thanks your super fast response.

**Comment by jinsyu** [comment]
PolarQuestion,NestedQuestion need to have validate string parameter!

**Comment by Michelphoenix98** [comment]
I take it you wish to have more control over the structure of the object,
I've written an example called questionnaire_form that shows how to
manipulate the exposed state of the widget.
If this doesn't clear your doubts, please feel free to hit me up. I'll be
more than happy to help.

**Comment by Michelphoenix98** [comment]
The PolarQuestion and NestedQuestion class have a special parameter called
'isMandatory'. Set it to true if you wish to have it validated.

**Comment by jinsyu** [comment]
I mean it is not editable of string. i am not making english based app. so it looks strange.

**Comment by jinsyu** [comment]
sorry to bother you, almost every asking is already written in your examples!!! you're my heroes.

**Comment by Michelphoenix98** [comment]
I see the issue now, I've basically hard coded the string at line 246 of
widget.dart. I'll be sure to add support for editing it soon. In
the meantime, feel free to fork the repo and make modifications as you see
fit.

**Comment by Michelphoenix98** [comment]
I'm glad I could help you :)
